import { SObjectDescribeResult } from "../types.js";
import {
  BAL_SALESFORCE_CONNECTOR_VERSION,
  BAL_DISTRIBUTION,
  MAX_FIELDS_PER_TYPE,
  SF_API_VERSION,
  SF_LOGIN_URL,
  SF_SANDBOX_LOGIN_URL,
  DEFAULT_SERVICE_PORT,
  isCustomObject,
} from "../constants.js";

// ─── Ballerina.toml ───────────────────────────────────────────────────────────

export function generateBallerinaToml(
  orgName: string,
  packageName: string,
  version: string
): string {
  return `[package]
org = "${orgName}"
name = "${packageName}"
version = "${version}"
distribution = "${BAL_DISTRIBUTION}"

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "${BAL_SALESFORCE_CONNECTOR_VERSION}"
`;
}

// ─── Config.toml ──────────────────────────────────────────────────────────────

export function generateConfigToml(
  clientId: string,
  clientSecret: string,
  refreshToken: string,
  baseUrl: string,
  port: number = DEFAULT_SERVICE_PORT,
  sandbox = false
): string {
  const refreshUrl =
    (sandbox ? SF_SANDBOX_LOGIN_URL : SF_LOGIN_URL) + "/services/oauth2/token";

  return `# Salesforce OAuth2 credentials — do NOT commit this file to version control
clientId     = "${escapeToml(clientId)}"
clientSecret = "${escapeToml(clientSecret)}"
refreshToken = "${escapeToml(stripNewlines(refreshToken))}"
refreshUrl   = "${refreshUrl}"
baseUrl      = "${escapeToml(baseUrl)}"
apiVersion   = "${SF_API_VERSION}"
servicePort  = ${port}
`;
}

// ─── .gitignore ───────────────────────────────────────────────────────────────

export function generateGitignore(): string {
  return `# Ballerina generated
target/
.ballerina/
Dependencies.toml

# Secrets — never commit
Config.toml
*.secret

# IDE
.idea/
.vscode/
`;
}

// ─── Type resolution per SObject ──────────────────────────────────────────────

/**
 * Decide how a generated route should refer to the record type for an SObject.
 * Standard SObjects use the pre-built type from `ballerinax/salesforce.types`,
 * which eliminates 95%+ of generated record boilerplate. Custom objects fall
 * back to a record we generate from the describe payload.
 */
export function recordTypeFor(objectName: string): {
  prebuilt: boolean;
  typeRef: string;
} {
  if (isCustomObject(objectName)) {
    return { prebuilt: false, typeRef: `${customRecordName(objectName)}` };
  }
  return { prebuilt: true, typeRef: `sftypes:${objectName}SObject` };
}

function customRecordName(objectName: string): string {
  // MyPkg__Foo__c → MyPkg_Foo_Record (Ballerina identifier-safe)
  return (
    objectName
      .replace(/__c$/i, "")
      .replace(/[^A-Za-z0-9]/g, "_")
      .replace(/^_+|_+$/g, "") + "Record"
  );
}

// ─── types.bal — custom record types only ────────────────────────────────────

export interface TypesFileResult {
  content: string;
  truncated: Array<{ object: string; total: number; emitted: number }>;
}

export function generateTypesFile(
  customDescribes: SObjectDescribeResult[]
): TypesFileResult {
  const truncated: TypesFileResult["truncated"] = [];

  if (customDescribes.length === 0) {
    return {
      content: `// Auto-generated by ballerina-salesforce-mcp-server.
// Standard SObjects use pre-built types from ballerinax/salesforce.types.
// Custom record types (if any) are declared below.
`,
      truncated,
    };
  }

  const lines: string[] = [
    "// Auto-generated by ballerina-salesforce-mcp-server",
    "// Custom SObject record type definitions",
    "",
  ];

  for (const obj of customDescribes) {
    const totalFields = obj.fields.length;
    const fields = obj.fields.slice(0, MAX_FIELDS_PER_TYPE);
    if (totalFields > MAX_FIELDS_PER_TYPE) {
      truncated.push({
        object: obj.name,
        total: totalFields,
        emitted: MAX_FIELDS_PER_TYPE,
      });
    }

    lines.push(`// ${obj.label} (${obj.name})`);
    if (totalFields > MAX_FIELDS_PER_TYPE) {
      lines.push(
        `// NOTE: truncated to first ${MAX_FIELDS_PER_TYPE} of ${totalFields} fields.`
      );
    }
    lines.push(`public type ${customRecordName(obj.name)} record {`);
    lines.push(`    string? Id = ();`);

    for (const f of fields) {
      if (f.name === "Id") continue;
      const balType = sfTypeToBal(f.type, f.nillable);
      lines.push(
        `    ${balType} ${sanitizeFieldName(f.name)} = ();   // ${f.label}`
      );
    }

    lines.push(`};`);
    lines.push("");
  }

  return { content: lines.join("\n"), truncated };
}

// ─── main.bal — service entry-point and shared SF client ─────────────────────

export function generateMainBal(
  orgName: string,
  packageName: string,
  objectNames: string[],
  servicePort: number = DEFAULT_SERVICE_PORT
): string {
  // We always import the types submodule — it's harmless if unused, and
  // keeps the file consistent across standard/custom mixes.
  const hasPrebuilt = objectNames.some((o) => !isCustomObject(o));

  const typesImport = hasPrebuilt
    ? `import ballerinax/salesforce.types as sftypes;`
    : "";

  const routes = objectNames
    .map((o) => {
      const snake = snakeCase(o);
      const { typeRef } = recordTypeFor(o);
      return `    // ${o} routes
    resource function get ${snake}s() returns json|error {
        return check query${safeId(o)}Records();
    }
    resource function get ${snake}/[string id]() returns json|error {
        return check get${safeId(o)}RecordById(id);
    }
    resource function post ${snake}(${typeRef} body) returns json|error {
        return check create${safeId(o)}Record(body);
    }
    resource function put ${snake}/[string id](${typeRef} body) returns json|error {
        return check update${safeId(o)}Record(id, body);
    }
    resource function delete ${snake}/[string id]() returns json|error {
        return check delete${safeId(o)}Record(id);
    }`;
    })
    .join("\n\n");

  return `import ballerina/http;
import ballerina/log;
import ballerina/os;
import ballerinax/salesforce;
${typesImport}

// ── Configurable variables (Config.toml or env vars) ────────────────────────
// Falls back to environment variables so the same project runs locally,
// in containers, or in WSO2 BI runtime without editing Config.toml.
configurable string clientId     = os:getEnv("SF_CLIENT_ID");
configurable string clientSecret = os:getEnv("SF_CLIENT_SECRET");
configurable string refreshToken = os:getEnv("SF_REFRESH_TOKEN");
configurable string refreshUrl   = os:getEnv("SF_REFRESH_URL");
configurable string baseUrl      = os:getEnv("SF_BASE_URL");
configurable string apiVersion   = "${SF_API_VERSION}";
configurable int    servicePort  = ${servicePort};

// ── Startup validation ───────────────────────────────────────────────────────
// Fail fast with a clear message if credentials are missing, instead of
// surfacing an opaque connector error on the first request.
function init() returns error? {
    if clientId == "" || clientSecret == "" || refreshToken == "" || baseUrl == "" {
        return error("Missing Salesforce credentials. Set them in Config.toml or via " +
            "env vars: SF_CLIENT_ID, SF_CLIENT_SECRET, SF_REFRESH_TOKEN, SF_BASE_URL " +
            "(refreshUrl optional — defaults to login.salesforce.com).");
    }
    log:printInfo("Starting Salesforce integration", servicePort = servicePort, baseUrl = baseUrl);
}

// ── Salesforce client ────────────────────────────────────────────────────────

final salesforce:ConnectionConfig sfConfig = {
    baseUrl: baseUrl,
    auth: {
        clientId:     clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl:   refreshUrl
    },
    apiVersion: apiVersion
};

final salesforce:Client sfClient = check new (sfConfig);

// ── HTTP listener ────────────────────────────────────────────────────────────
listener http:Listener httpListener = new (servicePort);

// ── Service router ───────────────────────────────────────────────────────────
service / on httpListener {

    resource function get health() returns json {
        log:printInfo("Health check OK");
        return { status: "UP", package: "${orgName}/${packageName}" };
    }

${routes}
}
`;
}

/**
 * Per-object CRUD file. Lives in the same default module as main.bal,
 * so the shared `sfClient` and `sftypes:` import are visible.
 */
export function generateObjectModule(objectName: string): string {
  const { prebuilt, typeRef } = recordTypeFor(objectName);
  const fnSuffix = safeId(objectName);
  const typesImport = prebuilt
    ? "// Uses pre-built record type from ballerinax/salesforce.types (imported in main.bal)."
    : "// Uses generated custom record type defined in types.bal.";

  return `// ── ${objectName} CRUD operations ───────────────────────────────────────────
${typesImport}

public function query${fnSuffix}Records() returns json|error {
    string soql = "SELECT FIELDS(STANDARD) FROM ${objectName} LIMIT 200";
    stream<record {}, error?> resultStream = check sfClient->query(soql);
    record {}[] records = [];
    check from record {} rec in resultStream
        do {
            records.push(rec);
        };
    return records.toJson();
}

public function get${fnSuffix}RecordById(string id) returns json|error {
    ${typeRef} rec = check sfClient->getById("${objectName}", id);
    return rec.toJson();
}

public function create${fnSuffix}Record(${typeRef} payload) returns json|error {
    var res = check sfClient->create("${objectName}", payload);
    return { id: res.id, success: true };
}

public function update${fnSuffix}Record(string id, ${typeRef} payload) returns json|error {
    check sfClient->update("${objectName}", id, payload);
    return { id: id, success: true };
}

public function delete${fnSuffix}Record(string id) returns json|error {
    check sfClient->delete("${objectName}", id);
    return { id: id, success: true };
}
`;
}

// ─── CDC / Platform Events listener ──────────────────────────────────────────

export type CdcEventType = "onCreate" | "onUpdate" | "onDelete" | "onRestore";

export interface CdcListenerOptions {
  /** SObject API name for CDC, e.g. "Account". Mutually exclusive with `allChanges` and `platformEvent`. */
  sobject?: string;
  /** Listen on /data/ChangeEvents (all CDC-enabled objects). */
  allChanges?: boolean;
  /** Platform event API name (ends with __e), e.g. "MyEvent__e". */
  platformEvent?: string;
  /** Which CDC callbacks to scaffold. Defaults to all four. Ignored for platform events. */
  events?: CdcEventType[];
}

/**
 * Generates a Ballerina file declaring a `salesforce:Listener` and either a
 * `CdcService` or `PlatformEventsService` for the chosen channel. The shared
 * SF credentials configured in main.bal are reused.
 *
 * Channel name follows the WSO2 BI docs:
 *   - Object CDC:       /data/<SObjectName>ChangeEvent
 *   - All CDC events:   /data/ChangeEvents
 *   - Platform event:   /event/<Name>__e
 */
export function generateCdcListener(opts: CdcListenerOptions): {
  filename: string;
  content: string;
} {
  if (opts.platformEvent) {
    return generatePlatformEventListener(opts.platformEvent);
  }

  const channel = opts.allChanges
    ? "/data/ChangeEvents"
    : `/data/${opts.sobject}ChangeEvent`;

  const events: CdcEventType[] =
    opts.events && opts.events.length > 0
      ? opts.events
      : ["onCreate", "onUpdate", "onDelete", "onRestore"];

  const label = opts.allChanges ? "AllChangeEvents" : opts.sobject!;
  const filename = `cdc_${snakeCase(label)}.bal`;

  const callbacks = events
    .map(
      (e) => `    remote function ${e}(salesforce:EventData event) returns error? {
        log:printInfo("${label} ${e}", event = event);
    }`
    )
    .join("\n\n");

  const content = `// ── CDC listener for ${channel} ─────────────────────────
import ballerina/log;
import ballerinax/salesforce;

// Reuses the OAuth2 credentials configured in main.bal (clientId/secret/refreshToken/refreshUrl/baseUrl).
listener salesforce:Listener ${cdcListenerVar(label)} = new ({
    auth: {
        clientId:     clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl:   refreshUrl
    },
    baseUrl: baseUrl,
    channelName: "${channel}"
});

service salesforce:CdcService on ${cdcListenerVar(label)} {
${callbacks}
}
`;

  return { filename, content };
}

function generatePlatformEventListener(eventName: string): {
  filename: string;
  content: string;
} {
  const channel = `/event/${eventName}`;
  const safeName = safeId(eventName);
  const filename = `event_${snakeCase(eventName)}.bal`;

  const content = `// ── Platform Event listener for ${channel} ─────────────
import ballerina/log;
import ballerinax/salesforce;

listener salesforce:Listener platformEventListener_${safeName} = new ({
    auth: {
        clientId:     clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl:   refreshUrl
    },
    baseUrl: baseUrl,
    channelName: "${channel}"
});

service salesforce:PlatformEventsService on platformEventListener_${safeName} {
    remote function onMessage(salesforce:PlatformEventsMessage event) returns error? {
        log:printInfo("Platform event ${eventName}", event = event);
    }
}
`;

  return { filename, content };
}

function cdcListenerVar(label: string): string {
  return `cdcListener_${safeId(label)}`;
}

// ─── README.md ────────────────────────────────────────────────────────────────

export function generateReadme(
  orgName: string,
  packageName: string,
  biPath: string,
  objectNames: string[]
): string {
  const fileTree = objectNames
    .map((o) => `├── ${snakeCase(o)}.bal`)
    .join("\n");

  const endpoints = objectNames
    .map((o) => {
      const s = snakeCase(o);
      return `| GET | /${s}s | Query ${o} records |
| POST | /${s} | Create a ${o} record |
| PUT | /${s}/{id} | Update a ${o} record |
| DELETE | /${s}/{id} | Delete a ${o} record |`;
    })
    .join("\n");

  return `# ${packageName}

Auto-generated Ballerina integration project for Salesforce.
Generated by **ballerina-salesforce-mcp-server** and ready to open in WSO2 Integrator (BI).

Uses **\`ballerinax/salesforce\` v${BAL_SALESFORCE_CONNECTOR_VERSION}** with
distribution **\`${BAL_DISTRIBUTION}\`**. Standard SObjects use the connector's
pre-built record types from \`ballerinax/salesforce.types\` — no hand-rolled
type stubs to maintain.

## Prerequisites

- Ballerina distribution \`${BAL_DISTRIBUTION}\` ([ballerina.io](https://ballerina.io/downloads/))
- WSO2 Integrator (BI) VS Code extension
- Salesforce Connected App with OAuth2 credentials

## Project Structure

\`\`\`
${packageName}/
├── Ballerina.toml
├── Config.toml          # gitignored
├── .gitignore
├── main.bal             # HTTP service + SF client
├── types.bal            # Custom record types only (standard SObjects use sftypes:*SObject)
${fileTree}
\`\`\`

## Covered SObjects

${objectNames.map((o) => `- \`${o}\``).join("\n")}

## Running Locally

\`\`\`bash
cd ${biPath}/${packageName}
bal run
\`\`\`

Or set environment variables (no Config.toml needed):

\`\`\`bash
export SF_CLIENT_ID=...
export SF_CLIENT_SECRET=...
export SF_REFRESH_TOKEN=...
export SF_REFRESH_URL=https://login.salesforce.com/services/oauth2/token
export SF_BASE_URL=https://myorg.my.salesforce.com
bal run
\`\`\`

## Opening in WSO2 Integrator (BI)

1. Launch VS Code with the **Ballerina Integrator** extension installed.
2. **File → Open Folder** → select \`${biPath}/${packageName}\`.
3. Click the BI icon in the Activity Bar.

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | /health | Health check |
${endpoints}
`;
}

// ─── Utility helpers ──────────────────────────────────────────────────────────

export function snakeCase(name: string): string {
  return name
    .replace(/__c$/i, "")
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "")
    .replace(/__+/g, "_");
}

/**
 * Identifier-safe transform for function names (e.g. MyPkg__Foo__c → MyPkg_Foo).
 * Exported so the tools layer can mirror what the generator emits without
 * duplicating the regex (single source of truth).
 */
export function safeId(objectName: string): string {
  return objectName
    .replace(/__c$/i, "")
    .replace(/[^A-Za-z0-9]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * Ballerina reserved words that cannot be used as bare identifiers.
 * When a Salesforce field name collides with one of these, we prefix it
 * with a single quote so Ballerina treats it as a quoted identifier.
 * Reference: https://ballerina.io/spec/lang/master/#section_3.1
 */
const BAL_KEYWORDS = new Set([
  "abstract", "anydata", "boolean", "break", "byte", "check", "checkpanic",
  "class", "client", "commit", "configurable", "conflict", "const",
  "decimal", "distinct", "do", "else", "enum", "error", "fail", "false",
  "final", "float", "flush", "fork", "from", "function", "future",
  "handle", "if", "import", "in", "int", "intersect", "is", "isolated",
  "join", "json", "key", "let", "limit", "listener", "lock", "map",
  "match", "module", "never", "new", "null", "object", "on", "order",
  "outer", "panic", "readonly", "record", "remote", "resource", "retry",
  "return", "returns", "rollback", "select", "service", "start", "stream",
  "string", "table", "transaction", "trap", "true", "type", "typedesc",
  "union", "var", "wait", "where", "while", "worker", "xml",
]);

function sanitizeFieldName(name: string): string {
  const sanitized = name.replace(/__c$/i, "").replace(/[^a-zA-Z0-9_]/g, "_");
  // Escape reserved words so generated Ballerina code compiles cleanly.
  return BAL_KEYWORDS.has(sanitized) ? `'${sanitized}` : sanitized;
}

function sfTypeToBal(sfType: string, nillable: boolean): string {
  const optional = nillable ? "?" : "";
  const mapping: Record<string, string> = {
    string: `string${optional}`,
    textarea: `string${optional}`,
    id: `string${optional}`,
    reference: `string${optional}`,
    picklist: `string${optional}`,
    multipicklist: `string${optional}`,
    phone: `string${optional}`,
    url: `string${optional}`,
    email: `string${optional}`,
    boolean: `boolean${optional}`,
    int: `int${optional}`,
    integer: `int${optional}`,
    double: `decimal${optional}`,
    currency: `decimal${optional}`,
    percent: `decimal${optional}`,
    date: `string${optional}`,
    datetime: `string${optional}`,
    time: `string${optional}`,
    base64: `string${optional}`,
  };
  return mapping[sfType.toLowerCase()] ?? `string${optional}`;
}

function escapeToml(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function stripNewlines(value: string): string {
  return value.replace(/[\r\n]+/g, "");
}
