import { SObjectDescribeResult } from "../types.js";
import {
  BAL_SALESFORCE_CONNECTOR_VERSION,
  BAL_DISTRIBUTION,
  MAX_FIELDS_PER_TYPE,
  SF_API_VERSION,
  SF_LOGIN_URL,
  SF_SANDBOX_LOGIN_URL,
  DEFAULT_SERVICE_PORT,
  isCustomObject,
} from "../constants.js";

// ─── Ballerina.toml ───────────────────────────────────────────────────────────

export function generateBallerinaToml(
  orgName: string,
  packageName: string,
  version: string
): string {
  return `[package]
org = "${orgName}"
name = "${packageName}"
version = "${version}"
distribution = "${BAL_DISTRIBUTION}"

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "${BAL_SALESFORCE_CONNECTOR_VERSION}"
`;
}

// ─── Config.toml ──────────────────────────────────────────────────────────────

export function generateConfigToml(
  clientId: string,
  clientSecret: string,
  refreshToken: string,
  baseUrl: string,
  port: number = DEFAULT_SERVICE_PORT,
  sandbox = false,
  orgName = "wso2bi",
  packageName = "salesforce_integration",
  includePort = true
): string {
  // Refresh tokens are bound to the host that issued them. The OAuth authorize
  // + code exchange run against the org's My Domain host (baseUrl), so the
  // connector must refresh at THAT same host — refreshing a My Domain token at
  // login.salesforce.com returns invalid_grant ("expired access/refresh token"),
  // which silently breaks the CDC listeners on first use. Derive the token
  // endpoint from baseUrl; fall back to the login/test host only if baseUrl
  // can't be parsed.
  let refreshUrl;
  try {
    refreshUrl = new URL(baseUrl).origin + "/services/oauth2/token";
  } catch {
    refreshUrl =
      (sandbox ? SF_SANDBOX_LOGIN_URL : SF_LOGIN_URL) + "/services/oauth2/token";
  }

  // apiVersion / servicePort only matter for the REST API (sfClient + http
  // listener). A portless CDC-only project declares neither configurable, so
  // omitting them here avoids "unmatched configuration" warnings at startup.
  const restConfig = includePort
    ? `apiVersion   = "${SF_API_VERSION}"\nservicePort  = ${port}\n`
    : "";

  return `# Salesforce OAuth2 credentials — do NOT commit this file to version control
[${orgName}.${packageName}]
clientId     = "${escapeToml(clientId)}"
clientSecret = "${escapeToml(clientSecret)}"
refreshToken = "${escapeToml(stripNewlines(refreshToken))}"
refreshUrl   = "${refreshUrl}"
baseUrl      = "${escapeToml(baseUrl)}"
${restConfig}`;
}

// ─── .gitignore ───────────────────────────────────────────────────────────────

export function generateGitignore(): string {
  return `# Ballerina generated
target/
.ballerina/
Dependencies.toml

# Secrets — never commit
Config.toml
*.secret

# IDE
.idea/
.vscode/
`;
}

// ─── Type resolution per SObject ──────────────────────────────────────────────

/**
 * Decide how a generated route should refer to the record type for an SObject.
 * Standard SObjects use the pre-built type from `ballerinax/salesforce.types`,
 * which eliminates 95%+ of generated record boilerplate. Custom objects fall
 * back to a record we generate from the describe payload.
 */
export function recordTypeFor(objectName: string): {
  prebuilt: boolean;
  typeRef: string;
} {
  if (isCustomObject(objectName)) {
    return { prebuilt: false, typeRef: `${customRecordName(objectName)}` };
  }
  return { prebuilt: true, typeRef: `sftypes:${objectName}SObject` };
}

function customRecordName(objectName: string): string {
  // MyPkg__Foo__c → MyPkg_Foo_Record (Ballerina identifier-safe)
  return (
    objectName
      .replace(/__c$/i, "")
      .replace(/[^A-Za-z0-9]/g, "_")
      .replace(/^_+|_+$/g, "") + "Record"
  );
}

// ─── types.bal — custom record types only ────────────────────────────────────

export interface TypesFileResult {
  content: string;
  truncated: Array<{ object: string; total: number; emitted: number }>;
}

export function generateTypesFile(
  customDescribes: SObjectDescribeResult[]
): TypesFileResult {
  const truncated: TypesFileResult["truncated"] = [];

  if (customDescribes.length === 0) {
    return {
      content: `// Auto-generated by ballerina-salesforce-mcp-server.
// Standard SObjects use pre-built types from ballerinax/salesforce.types.
// Custom record types (if any) are declared below.
`,
      truncated,
    };
  }

  const lines: string[] = [
    "// Auto-generated by ballerina-salesforce-mcp-server",
    "// Custom SObject record type definitions",
    "",
  ];

  for (const obj of customDescribes) {
    const totalFields = obj.fields.length;
    const fields = obj.fields.slice(0, MAX_FIELDS_PER_TYPE);
    if (totalFields > MAX_FIELDS_PER_TYPE) {
      truncated.push({
        object: obj.name,
        total: totalFields,
        emitted: MAX_FIELDS_PER_TYPE,
      });
    }

    lines.push(`// ${obj.label} (${obj.name})`);
    if (totalFields > MAX_FIELDS_PER_TYPE) {
      lines.push(
        `// NOTE: truncated to first ${MAX_FIELDS_PER_TYPE} of ${totalFields} fields.`
      );
    }
    lines.push(`public type ${customRecordName(obj.name)} record {`);
    lines.push(`    string? Id = ();`);

    for (const f of fields) {
      if (f.name === "Id") continue;
      const balType = sfTypeToBal(f.type, f.nillable);
      lines.push(
        `    ${balType} ${sanitizeFieldName(f.name)} = ();   // ${f.label}`
      );
    }

    lines.push(`};`);
    lines.push("");
  }

  return { content: lines.join("\n"), truncated };
}

// ─── main.bal — service entry-point and shared SF client ─────────────────────

export function generateMainBal(
  orgName: string,
  packageName: string,
  objectNames: string[],
  servicePort: number = DEFAULT_SERVICE_PORT,
  restApi: boolean = true
): string {
  // ── CDC-only (portless) variant ──────────────────────────────────────────
  // No http:Listener, no REST service, no sfClient — just the configurable
  // credentials the salesforce:Listener instances (cdc_*.bal) read at startup.
  // The CDC listeners themselves keep the runtime alive; no port is bound, so
  // there is no "Address already in use" failure mode.
  if (!restApi) {
    return `import ballerina/log;
import ballerina/os;

// ── Configurable variables (Config.toml or env vars) ────────────────────────
// Shared by every salesforce:Listener declared in the cdc_*.bal files.
configurable string clientId     = os:getEnv("SF_CLIENT_ID");
configurable string clientSecret = os:getEnv("SF_CLIENT_SECRET");
configurable string refreshToken = os:getEnv("SF_REFRESH_TOKEN");
configurable string refreshUrl   = os:getEnv("SF_REFRESH_URL");
configurable string baseUrl      = os:getEnv("SF_BASE_URL");

// ── Startup validation ───────────────────────────────────────────────────────
// Fail fast with a clear message if credentials are missing, instead of
// surfacing an opaque connector error when the CDC listeners start.
function init() returns error? {
    if clientId == "" || clientSecret == "" || refreshToken == "" || baseUrl == "" {
        return error("Missing Salesforce credentials. Set them in Config.toml or via " +
            "env vars: SF_CLIENT_ID, SF_CLIENT_SECRET, SF_REFRESH_TOKEN, SF_BASE_URL.");
    }
    log:printInfo("Salesforce CDC integration starting. If the listeners show " +
        "invalid_grant, visit http://localhost:${servicePort}/auth/reauth to " +
        "reauthorize without a restart.", baseUrl = baseUrl);
}
`;
  }

  // ── REST API variant (default) ───────────────────────────────────────────
  // We always import the types submodule — it's harmless if unused, and
  // keeps the file consistent across standard/custom mixes.
  const hasPrebuilt = objectNames.some((o) => !isCustomObject(o));

  const typesImport = hasPrebuilt
    ? `import ballerinax/salesforce.types as sftypes;`
    : "";

  const routes = objectNames
    .map((o) => {
      const snake = snakeCase(o);
      const { typeRef } = recordTypeFor(o);
      return `    // ${o} routes
    resource function get ${snake}s() returns json|error {
        return check query${safeId(o)}Records();
    }
    resource function get ${snake}/[string id]() returns json|error {
        return check get${safeId(o)}RecordById(id);
    }
    resource function post ${snake}(${typeRef} body) returns json|error {
        return check create${safeId(o)}Record(body);
    }
    resource function put ${snake}/[string id](${typeRef} body) returns json|error {
        return check update${safeId(o)}Record(id, body);
    }
    resource function delete ${snake}/[string id]() returns json|error {
        return check delete${safeId(o)}Record(id);
    }`;
    })
    .join("\n\n");

  return `import ballerina/http;
import ballerina/log;
import ballerina/os;
import ballerinax/salesforce;
${typesImport}

// ── Configurable variables (Config.toml or env vars) ────────────────────────
// Falls back to environment variables so the same project runs locally,
// in containers, or in WSO2 BI runtime without editing Config.toml.
configurable string clientId     = os:getEnv("SF_CLIENT_ID");
configurable string clientSecret = os:getEnv("SF_CLIENT_SECRET");
configurable string refreshToken = os:getEnv("SF_REFRESH_TOKEN");
configurable string refreshUrl   = os:getEnv("SF_REFRESH_URL");
configurable string baseUrl      = os:getEnv("SF_BASE_URL");
configurable string apiVersion   = "${SF_API_VERSION}";
configurable int    servicePort  = ${servicePort};

// ── Startup validation ───────────────────────────────────────────────────────
// Fail fast with a clear message if credentials are missing, instead of
// surfacing an opaque connector error on the first request.
// ── Salesforce client ────────────────────────────────────────────────────────
// sfClient uses a Bearer-token placeholder at module-level startup so that the
// service can launch even when the OAuth2 refresh token is expired. Ballerina's
// http module (2.16+) eagerly validates OAuth2 credentials on http:Client
// construction; using a Bearer placeholder avoids that network round-trip.
// auth_recovery.bal replaces sfClient with a real OAuth2 client once the user
// completes the authorization code flow via GET /auth/callback.
salesforce:Client sfClient = check new ({
    baseUrl: baseUrl == "" ? "https://placeholder.salesforce.com" : baseUrl,
    auth: <http:BearerTokenConfig>{token: "pending-oauth2-reauth"},
    apiVersion: apiVersion
});

// ── Startup validation ───────────────────────────────────────────────────────
function init() returns error? {
    if clientId == "" || clientSecret == "" || refreshToken == "" || baseUrl == "" {
        return error("Missing Salesforce credentials. Set them in Config.toml or via " +
            "env vars: SF_CLIENT_ID, SF_CLIENT_SECRET, SF_REFRESH_TOKEN, SF_BASE_URL.");
    }
    // Publisher flow: swap the startup placeholder for a real OAuth2 refresh-token
    // client so the REST CRUD routes authenticate immediately with the configured
    // token. Done here (not at module level) so an expired token degrades to a
    // clear log + /auth/reauth recovery instead of crashing the launch.
    salesforce:Client|error publisher = new ({
        baseUrl: baseUrl,
        auth: <http:OAuth2RefreshTokenGrantConfig>{
            clientId:     clientId,
            clientSecret: clientSecret,
            refreshToken: refreshToken,
            refreshUrl:   refreshUrl
        },
        apiVersion: apiVersion
    });
    if publisher is salesforce:Client {
        sfClient = publisher;
        log:printInfo("Publisher sfClient initialised with OAuth2 refresh-token credentials");
    } else {
        log:printWarn("Publisher sfClient could not authenticate at startup (refresh token " +
            "may be expired). REST CRUD will fail until you visit http://localhost:" +
            servicePort.toString() + "/auth/reauth.", 'error = publisher);
    }
    log:printInfo("Salesforce integration starting — if CDC listeners or REST calls show " +
        "invalid_grant, visit http://localhost:" + servicePort.toString() +
        "/auth/reauth to reauthorize.", servicePort = servicePort, baseUrl = baseUrl);
}

// ── HTTP listener ────────────────────────────────────────────────────────────
listener http:Listener httpListener = new (servicePort);

// ── Service router ───────────────────────────────────────────────────────────
service / on httpListener {

    resource function get health() returns json {
        log:printInfo("Health check OK");
        return { status: "UP", package: "${orgName}/${packageName}" };
    }

${routes}
}
`;
}

/**
 * Per-object CRUD file. Lives in the same default module as main.bal, so the
 * module-level `sfClient` is visible. Imports, however, are file-scoped in
 * Ballerina, so the `sftypes` import is re-declared here when needed.
 */
export function generateObjectModule(objectName: string): string {
  const { prebuilt, typeRef } = recordTypeFor(objectName);
  const fnSuffix = safeId(objectName);
  // Imports in Ballerina are file-scoped, not module-scoped — every file that
  // references `sftypes:` must import the submodule itself. main.bal importing
  // it does NOT make it visible here. Custom-object types live in types.bal in
  // this same default module, so they need no import.
  const typesImport = prebuilt
    ? "import ballerinax/salesforce.types as sftypes;\n// Uses pre-built record type from ballerinax/salesforce.types."
    : "// Uses generated custom record type defined in types.bal.";

  return `// ── ${objectName} CRUD operations ───────────────────────────────────────────
${typesImport}

public function query${fnSuffix}Records() returns json|error {
    string soql = "SELECT FIELDS(STANDARD) FROM ${objectName} LIMIT 200";
    stream<record {}, error?> resultStream = check sfClient->query(soql);
    record {}[] records = [];
    check from record {} rec in resultStream
        do {
            records.push(rec);
        };
    return records.toJson();
}

public function get${fnSuffix}RecordById(string id) returns json|error {
    ${typeRef} rec = check sfClient->getById("${objectName}", id);
    return rec.toJson();
}

public function create${fnSuffix}Record(${typeRef} payload) returns json|error {
    var res = check sfClient->create("${objectName}", payload);
    return { id: res.id, success: true };
}

public function update${fnSuffix}Record(string id, ${typeRef} payload) returns json|error {
    check sfClient->update("${objectName}", id, payload);
    return { id: id, success: true };
}

public function delete${fnSuffix}Record(string id) returns json|error {
    check sfClient->delete("${objectName}", id);
    return { id: id, success: true };
}
`;
}

// ─── CDC / Platform Events listener ──────────────────────────────────────────

export type CdcEventType = "onCreate" | "onUpdate" | "onDelete" | "onRestore";

export interface CdcListenerOptions {
  /** SObject API name for CDC, e.g. "Account". Mutually exclusive with `allChanges` and `platformEvent`. */
  sobject?: string;
  /** Listen on /data/ChangeEvents (all CDC-enabled objects). */
  allChanges?: boolean;
  /** Platform event API name (ends with __e), e.g. "MyEvent__e". */
  platformEvent?: string;
  /** Which CDC callbacks to scaffold. Defaults to all four. Ignored for platform events. */
  events?: CdcEventType[];
}

/**
 * Generates a Ballerina file declaring a `salesforce:Listener` and either a
 * `CdcService` or `PlatformEventsService` for the chosen channel. The shared
 * SF credentials configured in main.bal are reused.
 *
 * Channel name follows the WSO2 BI docs:
 *   - Object CDC:       /data/<SObjectName>ChangeEvent
 *   - All CDC events:   /data/ChangeEvents
 *   - Platform event:   /event/<Name>__e
 */
export function generateCdcListener(opts: CdcListenerOptions): {
  filename: string;
  content: string;
} {
  if (opts.platformEvent) {
    return generatePlatformEventListener(opts.platformEvent);
  }

  const channel = opts.allChanges
    ? "/data/ChangeEvents"
    : `/data/${opts.sobject}ChangeEvent`;

  const events: CdcEventType[] =
    opts.events && opts.events.length > 0
      ? opts.events
      : ["onCreate", "onUpdate", "onDelete", "onRestore"];

  const label = opts.allChanges ? "AllChangeEvents" : opts.sobject!;
  const filename = `cdc_${snakeCase(label)}.bal`;

  // Callback bodies show how to access changedData — CDC payloads only include
  // the fields that actually changed, plus always-present header fields (Id, etc.).
  const callbackBodies: Record<string, string> = {
    onCreate: [
      `        map<json> changedData = event.changedData;`,
      `        log:printInfo("[${label}] record created", payload = changedData.toJson());`,
      `        // TODO: implement your create-event business logic`,
    ].join("\n"),
    onUpdate: [
      `        map<json> changedData = event.changedData;`,
      `        log:printInfo("[${label}] record updated", payload = changedData.toJson());`,
      `        // TODO: only changed fields are present in changedData — check before accessing`,
    ].join("\n"),
    onDelete: [
      `        // Delete events carry no changed fields — the deleted record's ID is`,
      `        // in the ChangeEventHeader (event.metadata.recordId), not changedData.`,
      `        string? recordId = event.metadata?.recordId;`,
      `        log:printInfo("[${label}] record deleted", recordId = recordId);`,
      `        // TODO: implement your delete-event business logic`,
    ].join("\n"),
    onRestore: [
      `        string? recordId = event.metadata?.recordId;`,
      `        log:printInfo("[${label}] record restored", recordId = recordId);`,
      `        // TODO: implement your restore-event business logic`,
    ].join("\n"),
  };

  // The salesforce:Service object type requires ALL four remote methods
  // (onCreate/onUpdate/onDelete/onRestore) — omitting any one fails compilation
  // with "service declaration does not implement all required constructs". So we
  // always emit all four. `events` only chooses which ones get the richer,
  // business-logic-ready body; the rest get a minimal no-op stub.
  const ALL_EVENTS: CdcEventType[] = ["onCreate", "onUpdate", "onDelete", "onRestore"];
  const selected = new Set(events);
  const callbacks = ALL_EVENTS
    .map((e) => {
      const body = selected.has(e)
        ? callbackBodies[e]
        : `        // Not selected at scaffold time. Salesforce CDC requires a handler for
        // every event type, so this is a no-op stub — add logic if you start
        // handling ${e} events.
        log:printDebug("[${label}] ${e} (unhandled)", event = event);`;
      return `    remote function ${e}(salesforce:EventData event) returns error? {
${body}
    }`;
    })
    .join("\n\n");

  // The channel name is part of the service path, not the listener config.
  // A separate salesforce:Listener instance is required per channel when OAuth2
  // coordination is active (each listener manages one CometD subscription).
  const configVar = `cdcConfig_${safeId(label)}`;
  const content = `// ── CDC listener for ${channel} ─────────────────────────
import ballerina/http;
import ballerina/log;
import ballerinax/salesforce;

// Reuses the OAuth2 credentials from main.bal (clientId/secret/refreshToken/refreshUrl/baseUrl).
// The explicit <http:OAuth2RefreshTokenGrantConfig> cast resolves the OAuth2Config union type.
salesforce:RestBasedListenerConfig ${configVar} = {
    auth: <http:OAuth2RefreshTokenGrantConfig>{
        clientId:     clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl:   refreshUrl
    },
    baseUrl: baseUrl
};

listener salesforce:Listener ${cdcListenerVar(label)} = new (${configVar});

service "${channel}" on ${cdcListenerVar(label)} {
${callbacks}
}
`;

  return { filename, content };
}

function generatePlatformEventListener(eventName: string): {
  filename: string;
  content: string;
} {
  const channel = `/event/${eventName}`;
  const safeName = safeId(eventName);
  const filename = `event_${snakeCase(eventName)}.bal`;

  const content = `// ── Platform Event listener for ${channel} ─────────────
import ballerina/http;
import ballerina/log;
import ballerinax/salesforce;

salesforce:RestBasedListenerConfig platformEventConfig_${safeName} = {
    auth: <http:OAuth2RefreshTokenGrantConfig>{
        clientId:     clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl:   refreshUrl
    },
    baseUrl: baseUrl
};

listener salesforce:Listener platformEventListener_${safeName} = new (platformEventConfig_${safeName});

service "${channel}" on platformEventListener_${safeName} {
    remote function onMessage(salesforce:PlatformEventsMessage event) returns error? {
        map<json> payload = event.payload;
        log:printInfo("[${eventName}] platform event received", payload = payload.toJson());
        // TODO: implement your platform event business logic
    }
}
`;

  return { filename, content };
}

function cdcListenerVar(label: string): string {
  return `cdcListener_${safeId(label)}`;
}

// ─── auth_recovery.bal ────────────────────────────────────────────────────────

/**
 * Generates the OAuth2 authorization code grant recovery service.
 * cdcListenerNames: list of CDC listener variable names (e.g. ["Account","Contact"])
 */
export function generateAuthRecovery(
  cdcListenerNames: string[],
  opts: { restApi?: boolean; port?: number } = {}
): string {
  const restApi = opts.restApi ?? true;
  const port = opts.port ?? DEFAULT_SERVICE_PORT;

  const applyListenerCalls = cdcListenerNames
    .map(
      (n) =>
        `    _applyToListener("${n}", cdcListener_${safeId(n)}, newToken);`
    )
    .join("\n");

  // REST projects reuse main.bal's `httpListener` and have an `sfClient` to
  // refresh. CDC-only projects have neither — so auth_recovery binds its OWN
  // listener (on a dedicated `reauthPort`) and skips the sfClient reinit. This
  // is the one case where a CDC-only project binds a port; it's the cost of an
  // in-process browser reauth endpoint.
  const serviceHeader = restApi
    ? `// Reuses the http:Listener and sfClient declared in main.bal.
service /auth on httpListener {`
    : `// CDC-only project: bind a dedicated listener purely for the reauth endpoints.
configurable int reauthPort = ${port};
listener http:Listener reauthListener = new (reauthPort);

service /auth on reauthListener {`;

  // Which port variable the redirect URIs reference.
  const portRef = restApi ? "servicePort" : "reauthPort";

  // sfClient reinit only applies to REST projects (CDC-only has no sfClient).
  const reinitCall = restApi ? "        check _reinitSfClient(newToken);\n" : "";
  const reinitFn = restApi
    ? `
// Apply the new refresh token to sfClient so REST calls use it immediately.
function _reinitSfClient(string newToken) returns error? {
    salesforce:Client|error newClient = new ({
        baseUrl: baseUrl,
        auth: <http:OAuth2RefreshTokenGrantConfig>{
            clientId:     clientId,
            clientSecret: clientSecret,
            refreshToken: newToken,
            refreshUrl:   refreshUrl
        },
        apiVersion: apiVersion
    });
    if newClient is salesforce:Client {
        sfClient = newClient;
        log:printInfo("sfClient reinitialised with new refresh token");
    } else {
        log:printError("sfClient reinit failed", 'error = newClient);
        return newClient;
    }
}
`
    : "";

  return `// ── OAuth2 Authorization Code Grant recovery ──────────────────────────────────
// When the CDC listeners report \`invalid_grant\`, the user visits
//   GET /auth/reauth   →  302 redirect to Salesforce login page
//   GET /auth/callback →  receives the auth code, exchanges it for a new
//                         refresh token, persists it to Config.toml, applies it
//                         to all running CDC listeners${restApi ? ", and reinitialises sfClient" : ""}.
// No service restart is required.
//
// One-time setup: add   http://localhost:<${portRef}>/auth/callback
// to the Connected App's "Callback URL" list in Salesforce Setup.

import ballerina/http;
import ballerina/io;
import ballerina/log;
import ballerinax/salesforce;

${serviceHeader}

    // Redirect the browser to the Salesforce authorization page.
    resource function get reauth(http:Caller caller, http:Request req) returns error? {
        string redirectUri = "http://localhost:" + ${portRef}.toString() + "/auth/callback";
        string authUrl = baseUrl + "/services/oauth2/authorize" +
            "?response_type=code" +
            "&client_id=" + clientId +
            "&redirect_uri=" + redirectUri +
            "&state=sf-reauth";

        http:Response redirect = new;
        redirect.statusCode = 302;
        redirect.setHeader("Location", authUrl);
        check caller->respond(redirect);
        log:printInfo("Redirecting browser to Salesforce for reauthorization");
    }

    // Salesforce returns here with ?code=<auth_code> after the user approves.
    resource function get callback(http:Caller caller, http:Request req) returns error? {
        string? codeParam = req.getQueryParamValue("code");
        if codeParam is () || codeParam == "" {
            string desc = req.getQueryParamValue("error_description") ?: "no code returned";
            log:printError("OAuth2 callback missing auth code: " + desc);
            http:Response errResp = new;
            errResp.statusCode = 400;
            errResp.setTextPayload("Authorization failed: " + desc, "text/plain");
            check caller->respond(errResp);
            return;
        }

        string newToken = check _exchangeCode(codeParam);
        log:printInfo("New refresh token obtained via authorization code exchange");

        check _updateConfigFile(newToken);
        _applyTokenToAllListeners(newToken);
${reinitCall}
        http:Response resp = new;
        resp.statusCode = 200;
        resp.setTextPayload(
            "<html><body>" +
            "<h2>&#x2713; Salesforce reauthorization successful</h2>" +
            "<p>New refresh token saved to Config.toml.</p>" +
            "<p>CDC listeners have been reconnected — no restart needed.</p>" +
            "<p>You can close this window.</p>" +
            "</body></html>",
            "text/html"
        );
        check caller->respond(resp);
    }
}

// Exchange an authorization code for tokens and return the new refresh token.
function _exchangeCode(string code) returns string|error {
    string tokenBase = _extractBase(refreshUrl);
    string tokenPath = refreshUrl.length() > tokenBase.length()
        ? refreshUrl.substring(tokenBase.length())
        : "/services/oauth2/token";

    string redirectUri = "http://localhost:" + ${portRef}.toString() + "/auth/callback";
    string body = "grant_type=authorization_code" +
        "&code=" + code +
        "&client_id=" + clientId +
        "&client_secret=" + clientSecret +
        "&redirect_uri=" + redirectUri;

    http:Client tokenClient = check new (tokenBase);
    http:Response resp = check tokenClient->post(tokenPath, body,
        {"Content-Type": "application/x-www-form-urlencoded"});

    if resp.statusCode != 200 {
        string raw = check resp.getTextPayload();
        return error("Token exchange failed (" + resp.statusCode.toString() + "): " + raw);
    }

    json payload = check resp.getJsonPayload();
    json rtJson = check payload.refresh_token;
    return check rtJson.ensureType(string);
}

// Overwrite the refreshToken line in Config.toml with the new token.
function _updateConfigFile(string newToken) returns error? {
    string path = "./Config.toml";
    string content = check io:fileReadString(path);
    string updated = re \`refreshToken\\s*=\\s*"[^"]*"\`.replaceAll(
        content, "refreshToken = \\"" + newToken + "\\""
    );
    check io:fileWriteString(path, updated);
    log:printInfo("Config.toml updated with new refresh token");
}
${reinitFn}
// Call updateRefreshToken + reconnect on a single CDC listener.
function _applyToListener(string name, salesforce:Listener l, string newToken) {
    error? e = l.updateRefreshToken(newToken);
    if e is error {
        log:printError("updateRefreshToken failed", listenerName = name, 'error = e);
    }
    error? e2 = l.reconnect();
    if e2 is error {
        log:printError("reconnect failed", listenerName = name, 'error = e2);
    } else {
        log:printInfo("CDC listener reconnected with new refresh token", listenerName = name);
    }
}

// Apply the new token to every CDC listener declared in this module.
function _applyTokenToAllListeners(string newToken) {
${applyListenerCalls}
}

// Extract the scheme+host from a full URL.
isolated function _extractBase(string uri) returns string {
    int startIdx = uri.indexOf("://") ?: 0;
    if startIdx > 0 {
        startIdx = startIdx + 3;
    }
    int? slashIdx = uri.indexOf("/", startIdx);
    return slashIdx is int ? uri.substring(0, slashIdx) : uri;
}
`;
}

// ─── README.md ────────────────────────────────────────────────────────────────

export function generateReadme(
  orgName: string,
  packageName: string,
  biPath: string,
  objectNames: string[],
  opts: { restApi?: boolean; port?: number; cdcChannels?: string[] } = {}
): string {
  const restApi = opts.restApi ?? true;
  const port = opts.port ?? DEFAULT_SERVICE_PORT;
  const cdcChannels = opts.cdcChannels ?? [];

  const fileTree = objectNames
    .map((o) => `├── ${snakeCase(o)}.bal`)
    .join("\n");

  const endpoints = objectNames
    .map((o) => {
      const s = snakeCase(o);
      return `| GET | /${s}s | Query ${o} records |
| POST | /${s} | Create a ${o} record |
| PUT | /${s}/{id} | Update a ${o} record |
| DELETE | /${s}/{id} | Delete a ${o} record |`;
    })
    .join("\n");

  // ── Cheat-sheet sections ───────────────────────────────────────────────────
  const first = snakeCase(objectNames[0] ?? "account");
  const publisherSection = restApi
    ? `## Publisher flow — REST API

Create / read / update / delete Salesforce records over HTTP on **port ${port}**
(backed by \`sfClient\`, the \`ballerinax/salesforce\` connector).

| Method | Path | Action |
|--------|------|--------|
| GET | /health | Service health (\`{"status":"UP"}\`) |
${endpoints}

\`\`\`bash
# list records (SOQL under the hood)
curl http://localhost:${port}/${first}s

# create
curl -X POST http://localhost:${port}/${first} \\
  -H 'Content-Type: application/json' -d '{"Name":"Acme Corp"}'

# get one / update / delete
curl http://localhost:${port}/${first}/<id>
curl -X PUT http://localhost:${port}/${first}/<id> -H 'Content-Type: application/json' -d '{"Name":"New Name"}'
curl -X DELETE http://localhost:${port}/${first}/<id>
\`\`\`
`
    : `## Publisher flow

Not enabled in this project (\`rest_api = false\`). This is a CDC-only build —
see the consumer flow below. Re-scaffold with \`rest_api: true\` to add REST CRUD endpoints.
`;

  const consumerSection =
    cdcChannels.length > 0
      ? `## Consumer flow — Change Data Capture

Receives Salesforce change events via an outbound CometD subscription (no inbound
port). Each listener handles \`onCreate\` / \`onUpdate\` / \`onDelete\` / \`onRestore\`
(or \`onMessage\` for platform events) — edit the handler bodies in the \`cdc_*\`/\`event_*\` files.

| Channel | Listener file |
|---------|---------------|
${cdcChannels
  .map((c) => {
    const label = c.startsWith("/event/")
      ? c.slice("/event/".length)
      : c.startsWith("/data/") && c.endsWith("ChangeEvent")
      ? c.slice("/data/".length, -"ChangeEvent".length)
      : c === "/data/ChangeEvents"
      ? "AllChangeEvents"
      : c;
    const file = c.startsWith("/event/")
      ? `event_${snakeCase(label)}.bal`
      : `cdc_${snakeCase(label)}.bal`;
    return `| \`${c}\` | \`${file}\` |`;
  })
  .join("\n")}

> ⚠️ Enable each object in **Salesforce Setup → Change Data Capture** first, or the
> subscription is refused with \`403::Handshake denied\`.
`
      : "";

  const reauthSection = `## Reauthorize (token expired)

If the logs show \`invalid_grant\` or \`INVALID_SESSION_ID\`, open this once in a browser
to mint a fresh refresh token and hot-swap it into the ${restApi ? "REST client and " : ""}CDC
listeners — **no restart needed**:

\`\`\`
http://localhost:${port}/auth/reauth
\`\`\`

> Add \`http://localhost:${port}/auth/callback\` to the Connected App's Callback URL list.
> **Keep Refresh Token Rotation OFF** on the Connected App if you run the publisher and CDC
> together — they share one refresh token and rotation invalidates it.
`;

  return `# ${packageName}

Auto-generated Ballerina integration project for Salesforce.
Generated by **ballerina-salesforce-mcp-server** and ready to open in WSO2 Integrator (BI).

Uses **\`ballerinax/salesforce\` v${BAL_SALESFORCE_CONNECTOR_VERSION}** with
distribution **\`${BAL_DISTRIBUTION}\`**. Standard SObjects use the connector's
pre-built record types from \`ballerinax/salesforce.types\` — no hand-rolled
type stubs to maintain.

## Prerequisites

- Ballerina distribution \`${BAL_DISTRIBUTION}\` ([ballerina.io](https://ballerina.io/downloads/))
- WSO2 Integrator (BI) VS Code extension
- Salesforce Connected App with OAuth2 credentials

## Project Structure

\`\`\`
${packageName}/
├── Ballerina.toml
├── Config.toml          # gitignored
├── .gitignore
├── main.bal             # HTTP service + SF client
├── types.bal            # Custom record types only (standard SObjects use sftypes:*SObject)
${fileTree}
\`\`\`

## Covered SObjects

${objectNames.map((o) => `- \`${o}\``).join("\n")}

## Running Locally

\`\`\`bash
cd ${biPath}/${packageName}
bal run
\`\`\`

Or set environment variables (no Config.toml needed):

\`\`\`bash
export SF_CLIENT_ID=...
export SF_CLIENT_SECRET=...
export SF_REFRESH_TOKEN=...
export SF_REFRESH_URL=https://login.salesforce.com/services/oauth2/token
export SF_BASE_URL=https://myorg.my.salesforce.com
bal run
\`\`\`

## Opening in WSO2 Integrator (BI)

1. Launch VS Code with the **Ballerina Integrator** extension installed.
2. **File → Open Folder** → select \`${biPath}/${packageName}\`.
3. Click the BI icon in the Activity Bar.

${publisherSection}
${consumerSection}
${reauthSection}`;
}

// ─── Utility helpers ──────────────────────────────────────────────────────────

export function snakeCase(name: string): string {
  return name
    .replace(/__c$/i, "")
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "")
    .replace(/__+/g, "_");
}

/**
 * Identifier-safe transform for function names (e.g. MyPkg__Foo__c → MyPkg_Foo).
 * Exported so the tools layer can mirror what the generator emits without
 * duplicating the regex (single source of truth).
 */
export function safeId(objectName: string): string {
  return objectName
    .replace(/__c$/i, "")
    .replace(/[^A-Za-z0-9]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * Ballerina reserved words that cannot be used as bare identifiers.
 * When a Salesforce field name collides with one of these, we prefix it
 * with a single quote so Ballerina treats it as a quoted identifier.
 * Reference: https://ballerina.io/spec/lang/master/#section_3.1
 */
const BAL_KEYWORDS = new Set([
  "abstract", "anydata", "boolean", "break", "byte", "check", "checkpanic",
  "class", "client", "commit", "configurable", "conflict", "const",
  "decimal", "distinct", "do", "else", "enum", "error", "fail", "false",
  "final", "float", "flush", "fork", "from", "function", "future",
  "handle", "if", "import", "in", "int", "intersect", "is", "isolated",
  "join", "json", "key", "let", "limit", "listener", "lock", "map",
  "match", "module", "never", "new", "null", "object", "on", "order",
  "outer", "panic", "readonly", "record", "remote", "resource", "retry",
  "return", "returns", "rollback", "select", "service", "start", "stream",
  "string", "table", "transaction", "trap", "true", "type", "typedesc",
  "union", "var", "wait", "where", "while", "worker", "xml",
]);

function sanitizeFieldName(name: string): string {
  const sanitized = name.replace(/__c$/i, "").replace(/[^a-zA-Z0-9_]/g, "_");
  // Escape reserved words so generated Ballerina code compiles cleanly.
  return BAL_KEYWORDS.has(sanitized) ? `'${sanitized}` : sanitized;
}

function sfTypeToBal(sfType: string, nillable: boolean): string {
  const optional = nillable ? "?" : "";
  const mapping: Record<string, string> = {
    string: `string${optional}`,
    textarea: `string${optional}`,
    id: `string${optional}`,
    reference: `string${optional}`,
    picklist: `string${optional}`,
    multipicklist: `string${optional}`,
    phone: `string${optional}`,
    url: `string${optional}`,
    email: `string${optional}`,
    boolean: `boolean${optional}`,
    int: `int${optional}`,
    integer: `int${optional}`,
    double: `decimal${optional}`,
    currency: `decimal${optional}`,
    percent: `decimal${optional}`,
    date: `string${optional}`,
    datetime: `string${optional}`,
    time: `string${optional}`,
    base64: `string${optional}`,
  };
  return mapping[sfType.toLowerCase()] ?? `string${optional}`;
}

function escapeToml(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function stripNewlines(value: string): string {
  return value.replace(/[\r\n]+/g, "");
}
